Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbclient/client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
LABELS = dict(
    employment_income="Monthly employment income",
    dividend_income="Monthly dividend income",
    monthly_income="Monthly income",
    income_source="Income source",
    monthly_tanf="Monthly TANF allotment",
    mtr="Marginal tax rate from TANF?",
    allotment="TANF allotment",
    state_code="State",
)


def make_df(state_code, enrolled, vary_var):
    sim = IndividualSim(year=2022)
    sim.add_person(name="adult", age=30)
    sim.add_person(name="child", age=10)
    sim.add_spm_unit(
        name="spm_unit", members=["adult", "child"], is_tanf_enrolled=enrolled
    )
    sim.add_household(
        name="household", members=["adult", "child"], state_code=state_code
    )

    sim.vary(vary_var, max=1500 * 12, step=120)

    return pd.DataFrame(
        dict(
            monthly_income=sim.calc(vary_var)[0] / 12,
            enrolled="Enrolled" if enrolled else "Not Enrolled",
            state_code=state_code,
            monthly_tanf=sim.calc("tanf")[0] / 12,
            vary_var=vary_var,
            # mtr=-sim.deriv("tanf", "employment_income"),
        )
    )


fig = px.line(
    make_df("IL", True, "employment_income"),
    "monthly_income",
    "monthly_tanf",
    labels=LABELS,
    title="TANF allotment for a two-person household in Illinois",
)

fig.update_layout(xaxis_tickformat="$,", yaxis_tickformat="$,")
fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_2409/3582414565.py[0m in [0;36m<module>[0;34m[0m
[1;32m     45[0m [0;34m[0m[0m
[1;32m     46[0m [0mfig[0m[0;34m.[0m[0mupdate_layout[0m[0;34m([0m[0mxaxis_tickformat[0m[0;34m=[0m[0;34m"$,"[0m[0;34m,[0m [0myaxis_tickformat[0m[0;34m=[0m[0;34m"$,"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 47[0;31m [0mfig[0m[0;34m.[0m[0mshow[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/plotly/basedatatypes.py[0m in [0;36mshow[0;34m(self, *args, **kwargs)[0m
[1;32m   3396[0m         [0;32mimport[0m [0mplotly[0m[0;34m.[0m[0mio[0m [0;32mas[0m [0mpio[0m[0;34m[0m[0;34m[0m[0m
[1;32m   3397[0m [0;34m[0m[0m
[0;32m-> 3398[0;31m         [0;32mreturn[0m [0mpio[0m[0;34m.[0m[0mshow[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   3399[0m [0;34m[0m[0m
[1;32m   3400[0m     [0;32mdef[0m [0mto_json[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/site-packages/plotly/io/_renderers.py[0m in [0;36mshow[0;34m(fig, renderer, validate, **kwargs)[0m
[1;32m    395[0m         [0;32mif[0m [0;32mnot[0m [0mnbformat[0m [0;32mor[0m [0mLooseVersion[0m[0;34m([0m[0mnbformat[0m[0;34m.[0m[0m__version__[0m[0;34m)[0m [0;34m<[0m [0mLooseVersion[0m[0;34m([0m[0;34m"4.2.0"[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    396[0m             raise ValueError(
[0;32m--> 397[0;31m                 [0;34m"Mime type rendering requires nbformat>=4.2.0 but it is not installed"[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    398[0m             )
[1;32m    399[0m [0;34m[0m[0m

[0;31mValueError[0m: Mime type rendering requires nbformat>=4.2.0 but it is not installed
ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

